namespace SpriteKind {
    export const Menu = SpriteKind.create()
}
// CONTROLLER ACTION: PRESS B TO TOGGLE MAP VIEW
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (!(inMenu)) {
        Render.toggleViewMode()
    }
})
// Centers it perfectly
// CONTROLLER ACTION: PRESS A TO START
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (inMenu) {
        inMenu = false
        // Start the game!
        startGame()
        scene.setBackgroundImage(img`
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            ................................................................................................................................................................
            `)
    } else {
        Render.jump(mySprite)
    }
})
// THE MAIN GAMEPLAY SETUP
function startGame () {
    tiles.setCurrentTilemap(tilemap`level1`)
    mySprite = Render.getRenderSpriteVariable()
    tiles.placeOnRandomTile(mySprite, sprites.dungeon.darkGroundSouthEast1)
    Render.setViewMode(ViewMode.raycastingView)
    // Spawn Racket
    Racket = sprites.create(assets.image`Racket`, SpriteKind.Enemy)
    Racket.scale = 0.3
    Racket.setFlag(SpriteFlag.GhostThroughWalls, false)
    tiles.placeOnRandomTile(Racket, sprites.dungeon.darkGroundSouthEast1)
    Render.moveWithController(2)
    Racket.follow(mySprite, 30)
    Render.setViewAngleInDegree(110)
}
// WIN CONDITION (CHEST) & LOSE CONDITION (RACKET)
scene.onOverlapTile(SpriteKind.Player, sprites.dungeon.chestClosed, function (sprite, location) {
    game.gameOver(true)
    game.reset()
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    effects.clouds.startScreenEffect(1000)
    pause(1500)
    game.reset()
})
let Racket: Sprite = null
let mySprite: Sprite = null
let inMenu = false
Render.setViewMode(ViewMode.tilemapView)
scene.setBackgroundImage(img`
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffff2ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffff2fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffff2ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbebffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffff2ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbeeebffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffff2ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbeeeeebffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffff2fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbeeeeeebffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffff2fffffffffffffffffffffffff2ffffffffffffffffffffffffffffffffffffffffffffffffbbeeeeeeeeebfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffff2fffffffffffffff2fff22ffff22fffffffffffffffffffbbbbbbbbbbbbbbbbbbeeeeeeeeeeebfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffff2ffffffffffffff2ff22f22222f2222ffffffffffffffffbff11fffffffffffbeeeeeeeeeeeebfffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffff2ffffffffffffff2f2fff22222f22f2ffffffffffffffffbff111ffffffffffbeeeeeeeeeeeeebffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffff2fff2fffff22222222222222f22ffff2222ff22f2ffffffffffffffffbff1ff11ffffffffbeeeeeeeeeeeeebffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffff2ff2ffffffffffffffffffff2f22ffff22f2f22f2ffffffffffffffffbff1ffff11ffffffbeeeeeeeeeeeeebffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffff2f2fffffffffffffffffffff2f2f22ff222222ff2ffffffffffffffffbff1fffff1ffffffbeeeeeeeeeeeeebffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffff2f2fffffffffffffffffffff2ff2222222ff2f2f2fffff2ffffffffffb111fffff1ffffffbeeeeeeefffffeebffffffffffffffffffffffffff1ffffffffffffffffffffffffffff
    fffffffffffffffff2ffffffffffffff2fffff222fffffffffff2ff2fffffff2fffffffffbf11ffff1fffffffbeeeeeeefffffeebffffffffffffffffffffffffff1ffffffffffffffffffffffffffff
    fffffffffffffffff2ffffffffffffff222222ffffffffffffff2fff2fffff2ffffffffffbf11fff1ffffffffbeeeeeeefffffeebffffffffffffffffffffffffff1ffffffffffffffffffffffffffff
    fffffffffffffffff2fffffffffffffffffffffffffffffffffff2fff222222ffffffffffbf11ff1fffffffffbeeeeeeefffffeebffffffffffffffffffffffffff1ffffffffffffffffffffffffffff
    fffffffffffffffff2fffffffffffffffffffffffffffffffffff2fffffffffffffffffffbff111ffffffffffbeeeeeeefffffeeebfffffffffffffffffffffffff1ffffffffffffffffffffffffffff
    fffffffffffffffff2222222222222fffffffffffffffffffffff2fffffffffffffffffffbff111ffffffffffbeeeeeeeeeeeeeeebffffffffffffffffffffffffff1fffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffff2ffffffffffffffffffbff111111fffffffbeeeeeeeeeeeeeee11ffffffffffffffffff11fffff1fffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffff2ffffffffffffffffffbff11fff11ffffffbeeeeeeeeeeeeeee1b1ffffffff1ffffff11ff1ffff1fff1fffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffff22ffffffffffffffffbff11ffff1ffffffbeeeeeeee1eeeee1ebf1ffffff11f11fff1fff1ffff1ff11fffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff3ffffffffffffffbff11fffff1fffffbeeeeeee1eeeeee1ebff1fffff1f11f11f1f11ff1f1111fffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffff3fffff3ffff3ffffffffffffffbfff1ffffff1ffffbe1eeeee1eeeeee1ebfff1ffff1f11fff111ffff11f1fffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffff3fffff3f3ff3ffffffffffffffbfff1fffffff1fffb1e1eeee1eeeeee1ebfff1ffff1ff1fff111fff1ff1f1ffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffff3ffff3f3333ffffffffffffffbfff11ffffff1fffbe11111e1eeeeee1bffff1fffffffffffff1fff1ff1f1ffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffff3fff3333ff3ffffffffffffffbfff11fffffff1ffb1ee1e11e1eeebbf1ffff1fffffffffffff1fff1ff1f1ffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffff333ff33fff3fffffffffffffbfff11fffffff1ffb1eee1e11e1111fff1f11fffffffffffffff1f1ffff11ffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffff3ffff3fff3fffffffffffffbfff11fffffff1ffbe1ee1eee1bfff1fff11fffffff1ffffffff11fffff1f1fffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffff3ffff3fff3fffffffffffffbfff11ffffffff1fbe1e11eebbffff1ffff1ffffff1ffffffffffffffff1ff1ffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffff3fffffffff3ffffffffffffbfff11ffffffff1fbee1eebbffffff1fffff1ffff1fffffffffffffffffffff1fffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffff3fffffffff33333fffffffbffff1ffffffff1fbeeeebfffffff1fffffff11ff1fffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffff3fffffffffffffffffffffbffff11fffffff1fbeebbfffffff1ffffffffff11ffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbb1bbb1111bbbbbfffff1111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1111ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffff1111111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffff1ffffff1fffffffffffffffffffffffffffffffffffffffffffffff11ffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffff1ffff111fffffffffffffffffffffff1fffffffffffffffffffffff1f1fffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffff1fff11ffffffffffffffffffffffff1fff1111fffffffffffffffff1f1fffffffffffffffffffff1ffffffffff11ffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffff1ff1ffffffffffffffffffffffffff1fff11ffffffffffffffffff1fff1ffffffffffffffffffff1fffffffff111ffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffff1ffffffff1ffffffffff111ffffff1111f1ffffffffffffffffff1fff1ffffffffffffffffffff1fffffffff1f11fffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffff1fffff111f1111111ff1ff1fffffffff1ff1fffffffffffffffff1ffff1fffffffffffffffffff1fffffffff1ff1fffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffff1fffff1ffffffffff1111f1fffffffff1ff1fffffffffffffffff1ffff1fffffffffffffffffff1fffffffff1f1ffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffff11ffff1fffffffff1ffffffffffffff1fff1fffffffffffffffff11111f1ffffffffffffff1fff1ffffffff11f1ffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffff11fffff1ffffffff1fffffffff11111ffff1ffffffffffffffff1fffff1111fffffffffffff111111111111f11fffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffff1ffffffffffffff1ffffffffffffffffff1fffffffffffffff1ffffffff1fffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffff1fffffffffffff11f11ffffffffffffffffffffffff1fffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffff1ffffffffffffff11fffffffffffffffffffffffff11ffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffff111ffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffff1111ff1fffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffff111ffffffffffffffffffffffffffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffff1ffffffffffff1ffffffff11ffffffffffffffffffffffffffff1fffffffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffff11111111111ffffffffffff1ffffffffffff11ffff111fffffffffffffffffffff1fffffff1ff1fffffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffff1ffffffffffffffffffffff1ffffffffffff1f1fff1fffffffffffffffffffffff1fffff11fff1fffffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffff1ffffffffffffffffffffff1fffffffffff1ff1fff1fffffffffffffffffffffff1ffff1fffff1fffffffff11ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffff1fffffffffffffffffffff111111111fff1fff11ff1fffffffffffffffffffffff1ff11ffffff111ffffff11fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffff1ffffffffffffffffffffff1ffffffffff1f11ffff1fffffffffffffffffffffff111ffffffff111111111ff1111fffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffff1ffffffffffffffffffffff1fffffffff111ffffff1fffffffffffffffffffff11f1fffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffff1fffff1111fffffffffffff1ffffffffff1fffffff1ffffffffffffffffffffffff1fffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffff1ff111fffffffff11ffffff1fffffffffff11fffff1ffffffffffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffff1ffffffffffff11ff11ffff1fffffffffffff11fffffffffffffffffffffffffff1ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffff1fffffffffff1ffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffff1ff1111ffffffffffffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbebfffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbeeebfffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbeeeeebfffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbeeeeeebfffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbeeeeeeeeebffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbbbbbbbbbbbbbbbbbbeeeeeeeeeeebffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff11fffffffffffbeeeeeeeeeeeebffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff111ffffffffffbeeeeeeeeeeeeebfffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff1ff11ffffffffbeeeeeeeeeeeeebfffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff1ffff11ffffffbeeeeeeeeeeeeebfffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff1fffff1ffffffbeeeeeeeeeeeeebfffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb111fffff1ffffffbeeeeeeefffffeebffffffffffffffffffffffffff1fffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbf11ffff1fffffffbeeeeeeefffffeebffffffffffffffffffffffffff1fffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbf11fff1ffffffffbeeeeeeefffffeebffffffffffffffffffffffffff1fffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbf11ff1fffffffffbeeeeeeefffffeebffffffffffffffffffffffffff1fffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff111ffffffffffbeeeeeeefffffeeebfffffffffffffffffffffffff1fffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff111ffffffffffbeeeeeeeeeeeeeeebffffffffffffffffffffffffff1ffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff111111fffffffbeeeeeeeeeeeeeee11ffffffffffffffffff11fffff1ffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff11fff11ffffffbeeeeeeeeeeeeeee1b1ffffffff1ffffff11ff1ffff1fff1ffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff11ffff1ffffffbeeeeeeee1eeeee1ebf1ffffff11f11fff1fff1ffff1ff11ffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbff11fffff1fffffbeeeeeee1eeeeee1ebff1fffff1f11f11f1f11ff1f1111ffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfff1ffffff1ffffbe1eeeee1eeeeee1ebfff1ffff1f11fff111ffff11f1ffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfff1fffffff1fffb1e1eeee1eeeeee1ebfff1ffff1ff1fff111fff1ff1f1fffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffff1ffffffffffffffffffffffffffffbfff11ffffff1fffbe11111e1eeeeee1bffff1fffffffffffff1fff1ff1f1fffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfff11fffffff1ffb1ee1e11e1eeebbf1ffff1fffffffffffff1fff1ff1f1fffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfff11fffffff1ffb1eee1e11e1111fff1f11fffffffffffffff1f1ffff11fffffffffffffffffff
    ff1ffffffffffffffffffff111ffffffffffffffffffffffffffffffffffffffffffffffffffffffbfff11fffffff1ffbe1ee1eee1bfff1fff11fffffff1ffffffff11fffff1f1ffffffffffffffffff
    ff1fffffffffffffffffff1ff1ffffffff1fffffffff1fffffffffffffffffffffffffffffffffffbfff11ffffffff1fbe1e11eebbffff1ffff1ffffff1ffffffffffffffff1ff1fffffffffffffffff
    ff1ffffffffff11ffffff1ff1f1fff1fff1fffffffff1fffffffffffffffffffffffffffffff1fffbfff11ffffffff1fbee1eebbffffff1fffff1ffff1fffffffffffffffffffff1ffffffffffffffff
    ff1ff1fffff11ffffffff1ff1f1ff111ff1fffffffff1fffffffffffffffffffffffffffffff111fbffff1ffffffff1fbeeeebfffffff1fffffff11ff1ffffffffffffffffffffffffffffffffffffff
    ffff111ffff1fffffffff1ff1f1ff1f1ff1ffffffffff1ffffffffffffffffffffffffffffff11ffbffff11fffffff1fbeebbfffffff1ffffffffff11fffffffffffffffffffffffffffffffffffffff
    ffff1f1ffff1ffffffffffff111ff1ff1f1111f11111ff1f11fffffffffffff11ff1ffffffff11ffbbbbbb11bbbb11bbbbbfffff1111ffffffffffffffffffffffffffffffffffffffffffffffffffff
    fff1ff1ffff1ffffffffffff11ff11fff111fff111ffff11111ffff1fffffff111f1ffffffff1f1ffffffff1ff111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ff1ff1fffff11111ffffffff1ff11ffff1f1fff111ffff1111111fff1ff1fff11111ffffff1ff11fffffffff111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffff11fffff1fff1fffffffff11ffffff1f1fff1f1ffff1f1f1ff1fff1f11ff11f1f1f11ff11ff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffff1ffffff1111ffffffffffffffffffff1fff1f1ffff1f111ff11ff1f11fff1fff1f11ff111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffff1111ffffffffffffffffffffffffffffff1fffffff1f11fff1fff1fffffffff11ffffff1fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffff11fffffffffffffffffffffffffff111fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    `)
// TRACK GAME STATE
inMenu = true
mySprite = sprites.create(img`
    . 
    `, SpriteKind.Player)
Racket = sprites.create(img`
    . 
    `, SpriteKind.Enemy)
